create table tb_vendas (id int8 generated by default as identity, date date, fechamento int4, montante float8, visitado int4, vendedor_id int8, primary key (id));
create table tb_vendedores (id int8 generated by default as identity, name varchar(255), primary key (id));
alter table if exists tb_vendas add constraint FK9u55k6le8afh4a3haulsu4cc6 foreign key (vendedor_id) references tb_vendedores;
